site_name: Tarnished Engine Documentation
theme: readthedocs
site_url: https://TarnishedEngine.github.io/tengine-manual
repo_url: https://github.com/TarnishedEngine/tengine-manual

nav:
  - Home: index.md
  - About: about.md
  - TarnishedEngine Repositories: te-repos.md